export const NOTIFICATION_DATA = [
  {
    id: 1,
    date: "Today",
    time: "12:34pm",
    message:
      "Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin. Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin.",
    status: "unread",
  },
  {
    id: 2,
    date: "Today",
    time: "12:34pm",
    message:
      "Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin. Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin.",
    status: "unread",
  },
  {
    id: 3,
    date: "Today",
    time: "12:34pm",
    message:
      "Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin. Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin.",
    status: "unread",
  },
  {
    id: 4,
    date: "Today",
    time: "12:34pm",
    message:
      "Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin. Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin.",
    status: "read",
  },
  {
    id: 5,
    date: "Today",
    time: "12:34pm",
    message:
      "Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin. Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin.",
    status: "read",
  },
  {
    id: 6,
    date: "Today",
    time: "12:34pm",
    message:
      "Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin. Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin.",
    status: "read",
  },
  {
    id: 7,
    date: "Today",
    time: "12:34pm",
    message:
      "Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin. Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin.",
    status: "read",
  },
  {
    id: 8,
    date: "Today",
    time: "12:34pm",
    message:
      "Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin. Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin.",
    status: "read",
  },
  {
    id: 9,
    date: "Today",
    time: "12:34pm",
    message:
      "Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin. Sample notification Lorem ipsum dolor sit amet consectetur. Elit in id odio ut faucibus. Gravida sit quis cras sollicitudin.",
    status: "read",
  },
];

export const FAMILY_AND_FRIENDS_DATA = [
  { name: "Group A", value: 55 },
  { name: "Group B", value: 45 },
];

export const PROFILE_ORGANISATIONS_DATA = [
  {
    id: 1,
    name: "Access Bank",
    icon: "https://images.unsplash.com/photo-1611488006018-95b79a137ff5?q=80&w=2953&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 2,
    name: "Zenolynk",
    icon: "https://images.unsplash.com/photo-1569399078436-da10fbd60f12?q=80&w=2746&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

export const FAVOURITE_PROVIDERS_DATA = [
  {
    id: 1,
    name: "Jide Kosoko",
    occupation: "Psychologist",
    type: "individual",
    img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 2,
    name: "Jide Kosoko",
    occupation: "Psychologist",
    type: "individual",
    img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 3,
    name: "Jide Kosoko",
    occupation: "Psychologist",
    type: "individual",
    img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

export const DASHBOARD_STATS_DATA = [
  { id: 1, title: "Completed Appointments", value: 53 },
  { id: 2, title: "Upcoming Appointments", value: 53 },
  { id: 3, title: "Average Booking/Week", value: 3 },
];

export const TRANSACTIONS_DATA = [
  {
    id: 1,
    date: "Today",
    time: "12:34pm",
    description: "Fund Wallet",
    amount: "502,853",
    type: "credit",
    status: "success",
  },
  {
    id: 2,
    date: "Today",
    time: "12:34pm",
    description: "Appointment charge",
    amount: "502,853",
    type: "deduction",
    status: "failed",
  },
  {
    id: 3,
    date: "Today",
    time: "12:34pm",
    description: "Fund Wallet",
    amount: "502,853",
    type: "credit",
    status: "success",
  },
  {
    id: 4,
    date: "Today",
    time: "12:34pm",
    description: "Fund Wallet",
    amount: "502,853",
    type: "credit",
    status: "success",
  },
  {
    id: 5,
    date: "Today",
    time: "12:34pm",
    description: "Fund Wallet",
    amount: "502,853",
    type: "credit",
    status: "success",
  },
  {
    id: 6,
    date: "Today",
    time: "12:34pm",
    description: "Fund Wallet",
    amount: "502,853",
    type: "credit",
    status: "success",
  },
  {
    id: 7,
    date: "Today",
    time: "12:34pm",
    description: "Fund Wallet",
    amount: "502,853",
    type: "credit",
    status: "success",
  },
  {
    id: 8,
    date: "Today",
    time: "12:34pm",
    description: "Fund Wallet",
    amount: "502,853",
    type: "credit",
    status: "success",
  },
  {
    id: 9,
    date: "Today",
    time: "12:34pm",
    description: "Fund Wallet",
    amount: "502,853",
    type: "credit",
    status: "success",
  },
];

export const DEDUCTION_TRANSACTIONS_DATA = [
  {
    id: 1,
    date: "Today",
    time: "12:34pm",
    description: "Appointment charge",
    amount: "502,853",
    type: "deduction",
    status: "success",
  },
  {
    id: 2,
    date: "Today",
    time: "12:34pm",
    description: "Appointment charge",
    amount: "502,853",
    type: "deduction",
    status: "success",
  },
  {
    id: 3,
    date: "Today",
    time: "12:34pm",
    description: "Appointment charge",
    amount: "502,853",
    type: "deduction",
    status: "success",
  },
  {
    id: 4,
    date: "Today",
    time: "12:34pm",
    description: "Appointment charge",
    amount: "502,853",
    type: "deduction",
    status: "success",
  },
  {
    id: 5,
    date: "Today",
    time: "12:34pm",
    description: "Appointment charge",
    amount: "502,853",
    type: "deduction",
    status: "success",
  },
  {
    id: 6,
    date: "Today",
    time: "12:34pm",
    description: "Appointment charge",
    amount: "502,853",
    type: "deduction",
    status: "success",
  },
  {
    id: 7,
    date: "Today",
    time: "12:34pm",
    description: "Appointment charge",
    amount: "502,853",
    type: "deduction",
    status: "success",
  },
  {
    id: 8,
    date: "Today",
    time: "12:34pm",
    description: "Appointment charge",
    amount: "502,853",
    type: "deduction",
    status: "success",
  },
  {
    id: 9,
    date: "Today",
    time: "12:34pm",
    description: "Appointment charge",
    amount: "502,853",
    type: "deduction",
    status: "success",
  },
];

export const FAMILY_AND_FRIENDS_LIST = [
  {
    id: 1,
    date: "Today",
    time: "12:34pm",
    name: "James Dada",
    email: "example@email.com",
    relationship: "Friends",
  },
  {
    id: 2,
    date: "Today",
    time: "12:34pm",
    name: "James Dada",
    email: "example@email.com",
    relationship: "Family",
  },
  {
    id: 3,
    date: "Today",
    time: "12:34pm",
    name: "James Dada",
    email: "example@email.com",
    relationship: "Friends",
  },
  {
    id: 4,
    date: "Today",
    time: "12:34pm",
    name: "James Dada",
    email: "example@email.com",
    relationship: "Friends",
  },
  {
    id: 5,
    date: "Today",
    time: "12:34pm",
    name: "James Dada",
    email: "example@email.com",
    relationship: "Friends",
  },
  {
    id: 6,
    date: "Today",
    time: "12:34pm",
    name: "James Dada",
    email: "example@email.com",
    relationship: "Friends",
  },
  {
    id: 7,
    date: "Today",
    time: "12:34pm",
    name: "James Dada",
    email: "example@email.com",
    relationship: "Friends",
  },
  {
    id: 8,
    date: "Today",
    time: "12:34pm",
    name: "James Dada",
    email: "example@email.com",
    relationship: "Friends",
  },
  {
    id: 9,
    date: "Today",
    time: "12:34pm",
    name: "James Dada",
    email: "example@email.com",
    relationship: "Friends",
  },
];

export const FAMILY_AND_FRIENDS_APPOINTMENTS_DATA = [
  {
    id: 1,
    date: "Today",
    time: "12:34pm",
    consultant: "Adegboyoga Precious",
    booked_by: "Victor Adams",
    status: "upcoming",
  },
  {
    id: 2,
    date: "Today",
    time: "12:34pm",
    consultant: "Jide Kosoko",
    booked_by: "Victor Adams",
    status: "pending",
  },
  {
    id: 3,
    date: "Today",
    time: "12:34pm",
    consultant: "Nneka Chukwu",
    booked_by: "Victor Adams",
    status: "completed",
  },
  {
    id: 4,
    date: "Today",
    time: "12:34pm",
    consultant: "Adebayo Salami",
    booked_by: "Victor Adams",
    status: "canceled",
  },
  {
    id: 5,
    date: "Today",
    time: "12:34pm",
    consultant: "Desmond Tutu",
    booked_by: "Victor Adams",
    status: "completed",
  },
  {
    id: 6,
    date: "Today",
    time: "12:34pm",
    consultant: "Adebanji Bolaji",
    booked_by: "Victor Adams",
    status: "completed",
  },
  {
    id: 7,
    date: "Today",
    time: "12:34pm",
    consultant: "Baba Kaothat",
    booked_by: "Victor Adams",
    status: "completed",
  },
  {
    id: 8,
    date: "Today",
    time: "12:34pm",
    consultant: "Jibike Alarape",
    booked_by: "Victor Adams",
    status: "completed",
  },
  {
    id: 9,
    date: "Today",
    time: "12:34pm",
    consultant: "Eze Chinedu",
    booked_by: "Victor Adams",
    status: "completed",
  },
];

export const PROVIDERS_LIST = [
  {
    id: 1,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 2,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1496200186974-4293800e2c20?q=80&w=3132&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "organisation",
    name: "Leadway Health",
    title: "Psychology clinic",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 3,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 4,
    date: "Today",
    time: "12:34pm",
    img: "https://plus.unsplash.com/premium_photo-1673326679548-962d2fe77423?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "organisation",
    name: "Access Bank",
    title: "Financial Institution",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 5,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 6,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 7,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 8,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 9,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?q=80&w=2938&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "organisation",
    name: "Leadway Health",
    title: "Psychology clinic",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 10,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 11,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 12,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 13,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 14,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 15,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
];

export const PROVIDERS_UNDER_ORGANISATION_LIST = [
  {
    id: 1,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 2,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 3,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 4,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 5,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 6,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 7,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 8,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 9,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 10,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 11,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
  {
    id: 12,
    date: "Today",
    time: "12:34pm",
    img: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    type: "individual",
    name: "Jide Kosoko",
    title: "Psychologist",
    rating: "4.5",
    rate: "4,500",
  },
];
